### PR TITLE
Added beverages menu and updated "About Us" section and menu table

### PR DESCRIPTION
**Pull request by sittipat-chandang**
I've done the following:
- Added beverages menu.
- Updated "About Us" section in README.md.
- Updated menu table.

### CODE REVIEW

**Comment by Siraphop4Nene** [comment]
Good Menu and good mark down format

**Review by wave49192 — COMMENTED** [review]
Good Formatting!

**Review by Siraphop4Nene — APPROVED** [review]

**Review by wave49192 — APPROVED** [review]

**Review by sirateek — APPROVED** [review]
LGTM. 👍

**Review by NamoSmith — APPROVED** [review]
Good Job!

**Pull request merged**
