### PR TITLE
Add Breakfast Menu into `Menu.md`

### PR DESCRIPTION
**Pull request by sirateek**
## What have been implemented
1. Add breakfast menu in `Menu.md`
2. Add hyperlink and my role to `README.md`

### CODE REVIEW

**Comment by Siraphop4Nene** [comment]
Your menu make me hungry. Good work!!

**Comment by sittipat-chandang** [comment]
Excellent! Nice formatting.

**Review by wave49192 — COMMENTED** [review]
Good menu. Look tasty!

**Review by Siraphop4Nene — APPROVED** [review]

**Review by sittipat-chandang — APPROVED** [review]

**Review by NamoSmith — APPROVED** [review]
Nice!!

**Review by wave49192 — APPROVED** [review]

**Pull request merged**
